CREATE TABLE MCP_SERVER_STDIO (
    conversation_id VARCHAR(36) NOT NULL,
    content LONGVARCHAR NOT NULL,
    type VARCHAR(10) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX MCP_SERVER_STDIO_CONVERSATION_ID_TIMESTAMP_IDX ON MCP_SERVER_STDIO(conversation_id, timestamp DESC);

ALTER TABLE MCP_SERVER_STDIO ADD CONSTRAINT TYPE_CHECK CHECK (type IN ('USER', 'ASSISTANT', 'SYSTEM', 'TOOL'));
